name: Ansible deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
steps:
   - name: Run playbook
     with:
       playbook: play.yml
       inventory: |
         [52.59.251.179]
       key: ${{secrets.KEY}}
