name: Ansible Playbook
on:
  push:
    branches:
      - master

jobs:
  run-playbooks:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      with:
       playbook: play.yml
       key: ${{secrets.KEY}}
       inventory: |
         [52.59.251.179]
