name: Ansible deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run exporters playbook
      with:
        playbook: play.yml
        key: ${{secrets.KEY}}
        inventory: |
          [52.59.251.179]
