name: Ansible Playbook
on:
  push:
    branches:
      - master

jobs:
  run-playbooks:
    runs-on: self-hosted
    
    steps:
     - uses: actions/checkout@v2
     - name: Run Ansible Playbook
       run: ansible-playbook play.yaml
