name: Ansible Playbook
on:
  push:
    branches:
      - master

jobs:
  run-playbooks:
    runs-on: ubuntu-latest  
    steps:
    - name: Git Clone repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: |
        pwd
        ls -l
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Run Ansible-playbook
      run: |
        ansible-playbook play.yml
#       key: ${{secrets.KEY}}

    - name: version
      run: |
        ansible --version
        ansible localhost -m ping
        aws --version
