name: Ansible deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: run exporters playbook
      run: |
        ansible-playbook -i host play.yml
