name: Ansible Playbook
on: [push]

jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Execute Sample Playbook
    steps:
      - uses: actions/checkout@v1
      - name: Execute Playbook Action Step
        id: Execution
        uses: saubermacherag/ansible-playbook-docker-action@master
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
          ANSIBLE_FORCE_COLOR: true
        with:
          playbookName: "play.yml"
          inventoryFile: "hosts"
          keyFile: ${{ secrets.KEY }}
          keyFileVaultPass: ${{ secrets.KEY }}
