name: Ansible Playbook
on:
  push:
    branches:
      - master

jobs:
  run-playbooks:
    runs-on: ubuntu-latest  
    steps:
    - name: Git Clone repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: |
        pwd
        ls -l
#      run: |
#        ansible-playbook play.yml
#       key: ${{secrets.KEY}}
